version: '3.1'

services:
  db:
    image: mysql:9.2.0
    ports:
        - "3306:3306"
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: snippetbox
        MYSQL_USER: rm
        MYSQL_PASSWORD: rm
